name: GCSocketClient

on: [push]


jobs:
  GCSocketClient:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

